name: Publicar Resumen Diario
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Actualizado a v4
      - name: Set up Python
        uses: actions/setup-python@v5 # Actualizado a v5
        with:
          python-version: '3.11' # Subido a 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          IG_ACCOUNT_ID: ${{ secrets.IG_ACCOUNT_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: python src/main.py
      - name: Commit and Push image
        run: |
          git config --global user.name "ResumenIA-Bot"
          git config --global user.email "bot@resumenia.com"
          git add public/post_dia.jpg
          git commit -m "Nuevo post diario" || echo "No hay cambios"
          git push
